// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using entityDBtest;

namespace entityDBtest.Migrations
{
    [DbContext(typeof(CurrencyContext))]
    [Migration("20210128152412_CreateCurrencyDB")]
    partial class CreateCurrencyDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("entityDBtest.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateDateDate")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UpdateDateDate");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("entityDBtest.DateString", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Date");

                    b.ToTable("DateString");
                });

            modelBuilder.Entity("entityDBtest.Currency", b =>
                {
                    b.HasOne("entityDBtest.DateString", "UpdateDate")
                        .WithMany()
                        .HasForeignKey("UpdateDateDate");

                    b.Navigation("UpdateDate");
                });
#pragma warning restore 612, 618
        }
    }
}
