// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using entityDBtest;

namespace entityDBtest.Migrations
{
    [DbContext(typeof(CurrencyContext))]
    [Migration("20210128175958_CreateCurrencyDB")]
    partial class CreateCurrencyDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("entityDBtest.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(3)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<string>("UpdatedDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedDate");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("entityDBtest.Models.DateString", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("date");

                    b.HasKey("Date");

                    b.ToTable("DateString");
                });

            modelBuilder.Entity("entityDBtest.Models.Currency", b =>
                {
                    b.HasOne("entityDBtest.Models.DateString", "Updated")
                        .WithMany()
                        .HasForeignKey("UpdatedDate");

                    b.Navigation("Updated");
                });
#pragma warning restore 612, 618
        }
    }
}
