// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using entityDBtest;

namespace entityDBtest.Migrations
{
    [DbContext(typeof(CurrencyContext))]
    partial class CurrencyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("entityDBtest.Currency", b =>
                {
                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Rate")
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Date");

                    b.ToTable("Currency");
                });
#pragma warning restore 612, 618
        }
    }
}
